version 1.10
boyarintsev1/java-filmorate pull request #12
Opened 2023-11-19 20:59 UTC by boyarintsev1

2023-11-21 06:57 UTC, kriwsha requested changes

2023-11-21 06:57 UTC, kriwsha commented on bash.exe.stackdump
> +Stack trace:
Дамп можно удалить

2023-11-21 06:57 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/films")
Тут я с вами не соглашусь. @RequestMapping для класса более удобен с той точки зрения, что его сразу видно. Иными словами, вы открываете класс, и сразу видите, что все запросы только для пути, начинающегося с /films... В вашем случае другой разработчик может ошибиться и забыть поставить этот префикс к очередному методу, подумав, что предыдущий разработчик уже позаботился об этом (ведь так всегда делается). А потому будет долго ругаться на того разработчика, который не сделал, как всегда делается.

2023-11-21 06:57 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/genres")
Здесь я понял, почему вы убрали префикс фильмов, но так делать не надо! По этой логике сюда же и пользователей можно внести. Следует все таки разделить контроллер для фильмов и жанров.

2023-11-21 06:57 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      public User findUserById(@PathVariable("id") String id) {
Вы можете сразу поставить нужный тип данных для идентификатора

2023-11-21 06:57 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public static final String[] genres_names = {"Комедия", "Драма", "Мультфильм", "Триллер",
По правилам написания кода на Java константы должны быть полностью заглавными буквами. На некоторых проектах есть автоматические проверки. И такой пул реквест не пропустят

2023-11-21 06:57 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +                LocalDate birthday, Set<Long> friends) {  //, Set<Long> unconfirmedFriends
Не следует оставлять закомментированные куски кода

2023-11-21 06:57 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/service/Film/FilmDbService.java
> +            throw new IncorrectIdException("FilmID");
Вы здесь бросаете исключение с неким параметром. Потом отлавливаете и проверяете сообщение, а потом на основе этих параметров формируете новое сообщение. Исключение - это не объект передачи параметров. Следует уже здесь сформировать сообщение и уже там, где вы его отлавливаете, использовать готовое.

2023-11-21 06:57 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/service/Film/InMemoryFilmService.java
> +    public Collection<Film> findAllFilms() {                           // получение всех фильмов
У вас часть комментариев документирующие, часть простые. Давайте выберем единый стиль и желательно документирующий стиль.

2023-11-21 06:57 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/service/Film/InMemoryFilmService.java
> +            throw new IncorrectIdException("FilmID");
Здесь те же рекомендации, что и в другом сервисе

2023-11-21 06:57 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/service/User/UserDbService.java
> +            throw new IncorrectIdException("UserID");
Здесь так же

2023-11-21 06:57 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            throw new ValidationException("mpa_rating_id");
И здесь

2023-11-21 06:57 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new IncorrectIdException("Mpa");
И в этом классе

2023-11-21 06:57 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return (List<User>) users.values();
Не следует так приводить Set в List. Следует инициализировать ArrayList с помощью другой коллекции

2023-11-21 06:57 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            throw new ValidationException("email");
Здесь тоже нужно поправить сообщение

2023-11-21 17:00 UTC, boyarintsev1 commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public static final String[] genres_names = {"Комедия", "Драма", "Мультфильм", "Триллер",
Исправлено.

2023-11-21 17:01 UTC, boyarintsev1 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +                LocalDate birthday, Set<Long> friends) {  //, Set<Long> unconfirmedFriends
Исправлено.

2023-11-21 17:12 UTC, boyarintsev1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return (List<User>) users.values();
Исправлено

2023-11-21 17:57 UTC, boyarintsev1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      public User findUserById(@PathVariable("id") String id) {
Я был уверен, что здесь должно быть String, спасибо за поправку.
Иначе я бы ещё долго мучился.

2023-11-21 17:58 UTC, boyarintsev1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      public User findUserById(@PathVariable("id") String id) {
Исправлено.

2023-11-21 17:59 UTC, boyarintsev1 commented on bash.exe.stackdump
> +Stack trace:
Исправлено.

2023-11-21 21:12 UTC, boyarintsev1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/films")
Исправлено

2023-11-21 21:12 UTC, boyarintsev1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/genres")
Исправлено

2023-11-21 21:14 UTC, boyarintsev1 commented on src/main/java/ru/yandex/practicum/filmorate/service/Film/InMemoryFilmService.java
> +    public Collection<Film> findAllFilms() {                           // получение всех фильмов
Исправлено

2023-11-21 21:32 UTC, boyarintsev1 commented on src/main/java/ru/yandex/practicum/filmorate/service/Film/FilmDbService.java
> +            throw new IncorrectIdException("FilmID");
Уважаемый Владимир! Позвольте не согласиться. В данном случае "FilmID" вставляется в готовое сообщение и выводится на экран. На его основе НЕ формируется составное сообщение об ошибке.
Во время обучения сообщалось, что все пользовательские ошибки лучше всего собрать в ErrorHandler.
Почему лучше сразу передавать готовое сообщение?

2023-11-21 21:33 UTC, boyarintsev1 commented on src/main/java/ru/yandex/practicum/filmorate/service/Film/InMemoryFilmService.java
> +            throw new IncorrectIdException("FilmID");
Позвольте не согласиться. Та же самая ситуация, что я описал выше.

2023-11-21 21:33 UTC, boyarintsev1 commented on src/main/java/ru/yandex/practicum/filmorate/service/User/UserDbService.java
> +            throw new IncorrectIdException("UserID");
Позвольте не согласиться. Та же самая ситуация, что я описал выше, только UserID вместо FilmID

2023-11-21 21:34 UTC, boyarintsev1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new IncorrectIdException("Mpa");
Позвольте не согласиться. Та же самая ситуация, что я описал выше.

2023-11-21 21:35 UTC, boyarintsev1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            throw new ValidationException("email");
Позвольте не согласиться. Та же самая ситуация, но в данном случае у меня составное сообщение об ошибке.
Почему это не корректный вывод сообщения об ошибке?

2023-11-21 21:36 UTC, boyarintsev1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            throw new ValidationException("mpa_rating_id");
Позвольте не согласиться. Та же самая ситуация, что я описал выше.

2023-11-22 17:37 UTC, kriwsha approved these changes

2023-11-27 21:08 UTC, merged